---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codes-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codes-worker
  template:
    metadata:
      labels:
        app: codes-worker
    spec:
      containers:
      - name: codes-worker
        image: coupon-book-service:latest
        imagePullPolicy: Never
        command: ["node", "src/workers/rabbitMQ/rabbit-worker.js"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: codes-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: codes-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50